import { Patient } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'P001',
    name: 'Eleanor Vasquez',
    age: 54,
    gender: 'Female',
    bloodGroup: 'A+',
    diagnosis: 'Hypertensive Heart Disease',
    status: 'Stable',
    admittedOn: '2024-03-10',
    doctor: 'Dr. James Harlow',
    ward: 'Cardiology - Ward 3',
    phone: '+1 (555) 234-5678',
    email: 'e.vasquez@email.com',
    vitals: { heartRate: 78, bloodPressure: '128/82', temperature: 98.6, oxygenSaturation: 97 },
  },
  {
    id: 'P002',
    name: 'Marcus Chen',
    age: 38,
    gender: 'Male',
    bloodGroup: 'O+',
    diagnosis: 'Type 2 Diabetes Mellitus',
    status: 'Active',
    admittedOn: '2024-03-14',
    doctor: 'Dr. Priya Mehta',
    ward: 'Endocrinology - Ward 1',
    phone: '+1 (555) 345-6789',
    email: 'm.chen@email.com',
    vitals: { heartRate: 82, bloodPressure: '135/88', temperature: 99.1, oxygenSaturation: 96 },
  },
  {
    id: 'P003',
    name: 'Amara Okonkwo',
    age: 67,
    gender: 'Female',
    bloodGroup: 'B+',
    diagnosis: 'Acute Myocardial Infarction',
    status: 'Critical',
    admittedOn: '2024-03-18',
    doctor: 'Dr. Sarah Winters',
    ward: 'ICU - Bay 2',
    phone: '+1 (555) 456-7890',
    email: 'a.okonkwo@email.com',
    vitals: { heartRate: 102, bloodPressure: '160/100', temperature: 100.4, oxygenSaturation: 91 },
  },
  {
    id: 'P004',
    name: 'Rafael Torres',
    age: 29,
    gender: 'Male',
    bloodGroup: 'AB-',
    diagnosis: 'Pneumonia',
    status: 'Active',
    admittedOn: '2024-03-16',
    doctor: 'Dr. Emily Rhodes',
    ward: 'Pulmonology - Ward 2',
    phone: '+1 (555) 567-8901',
    email: 'r.torres@email.com',
    vitals: { heartRate: 94, bloodPressure: '118/76', temperature: 101.2, oxygenSaturation: 93 },
  },
  {
    id: 'P005',
    name: 'Ingrid Larsen',
    age: 45,
    gender: 'Female',
    bloodGroup: 'A-',
    diagnosis: 'Rheumatoid Arthritis',
    status: 'Stable',
    admittedOn: '2024-03-12',
    doctor: 'Dr. Nathan Cole',
    ward: 'Rheumatology - Ward 4',
    phone: '+1 (555) 678-9012',
    email: 'i.larsen@email.com',
    vitals: { heartRate: 72, bloodPressure: '120/78', temperature: 98.2, oxygenSaturation: 98 },
  },
  {
    id: 'P006',
    name: 'David Okwu',
    age: 72,
    gender: 'Male',
    bloodGroup: 'O-',
    diagnosis: 'COPD Exacerbation',
    status: 'Critical',
    admittedOn: '2024-03-17',
    doctor: 'Dr. Emily Rhodes',
    ward: 'ICU - Bay 5',
    phone: '+1 (555) 789-0123',
    email: 'd.okwu@email.com',
    vitals: { heartRate: 110, bloodPressure: '145/92', temperature: 100.8, oxygenSaturation: 88 },
  },
  {
    id: 'P007',
    name: 'Lily Nakamura',
    age: 33,
    gender: 'Female',
    bloodGroup: 'B-',
    diagnosis: 'Appendicitis (Post-Op)',
    status: 'Discharged',
    admittedOn: '2024-03-09',
    doctor: 'Dr. Alan Marsh',
    ward: 'Surgery - Ward 6',
    phone: '+1 (555) 890-1234',
    email: 'l.nakamura@email.com',
    vitals: { heartRate: 68, bloodPressure: '112/72', temperature: 98.0, oxygenSaturation: 99 },
  },
  {
    id: 'P008',
    name: 'Samuel Adeyemi',
    age: 58,
    gender: 'Male',
    bloodGroup: 'AB+',
    diagnosis: 'Chronic Kidney Disease Stage 3',
    status: 'Active',
    admittedOn: '2024-03-13',
    doctor: 'Dr. James Harlow',
    ward: 'Nephrology - Ward 2',
    phone: '+1 (555) 901-2345',
    email: 's.adeyemi@email.com',
    vitals: { heartRate: 86, bloodPressure: '140/90', temperature: 98.8, oxygenSaturation: 95 },
  },
];

export const mockMonthlyData = [
  { month: 'Sep', admissions: 210, discharges: 198, revenue: 485000 },
  { month: 'Oct', admissions: 245, discharges: 231, revenue: 542000 },
  { month: 'Nov', admissions: 228, discharges: 219, revenue: 513000 },
  { month: 'Dec', admissions: 189, discharges: 201, revenue: 467000 },
  { month: 'Jan', admissions: 267, discharges: 248, revenue: 598000 },
  { month: 'Feb', admissions: 291, discharges: 274, revenue: 634000 },
  { month: 'Mar', admissions: 312, discharges: 289, revenue: 681000 },
];

export const mockDepartmentStats = [
  { department: 'Cardiology', patients: 48, occupancy: 86 },
  { department: 'Pulmonology', patients: 32, occupancy: 74 },
  { department: 'Nephrology', patients: 27, occupancy: 69 },
  { department: 'Neurology', patients: 41, occupancy: 91 },
  { department: 'Oncology', patients: 55, occupancy: 95 },
  { department: 'Surgery', patients: 38, occupancy: 78 },
];
